### ISSUE TITLE
1.5

### ISSUE THREAD

**Issue by izaius** [aoloe/scribus-plugin-tableofcontents#5]
Is this project still alive? Any chance of it being released for 1.5?

**Comment by aoloe** [comment]
yes, it's alive... but i have no current use for it so it has low priority.

typically, it has been my second use case while (re) writing my plugin API and i'm working from time to time and i plan to get it to work (or to be stuck on a technical issue) before the next libre graphics meeting... end of mai... (the goal is to be able to show a prototype of the API to the team and get their feedback).

at the end of the day, it's more fun to work on task where other people collaborate and i'm more keen to work on things i need myself...

and for now, it's completely in time for the roadmap to 1.6: 1.6 will be released when it's ready and this plugin the same : - )

i'm closing this ticket since there is not much i can do for it, but your welcome to join the development with code or with ideas on how to achieve a TOC plugin that is as simple as possible!
